### ISSUE TITLE
Deadlocks when run from ghci

### ISSUE THREAD

**Issue by sol** [batterseapower/test-framework#14]
There are two issues when I run test suites with **failing** qc properties from ghci:
1. The counterexample is printed interleaved with normal test-framework output (sometimes it gets somewhere into the test label of the previous test, sometimes into an OK-bracket, etc.)
2. It sometimes deadlocks just after the first character of the counterexample has been printed (say the `"` for the example below)

Below is a minimal example (Just load it into ghci, and run `main` repetitively).

```
import Test.Framework
import Test.Framework.Providers.QuickCheck2 (testProperty)

main = defaultMain
  [ testProperty "reverse" prop_reverse
  , testProperty "foobar" (/= "")
  ]

prop_reverse :: [Int] -> Bool
prop_reverse xs = xs == (reverse . reverse) xs
```

**Comment by sol** [comment]
The interleaved output issue also occurs when a unit test writes to `stdout`.

**Comment by batterseapower** [comment]
I can't reproduce this with GHC 7.0.4 on OS X, either when running "main" repeatedly or by using "replicateM_ 1000 (do { main; return () } `Control.Exception.catch` (\e -> const (return ()) (e :: SomeException)))" to run it several times in a row.

You might try upgrading to 7.4, Simon Marlow fixed a scheduler bug which could cause deadlocks in that release.

**Comment by sol** [comment]
I tested this on Linux (with 7.0.4, I think).  I'll produce a test case, and try with other compiler versions.

**Comment by sol** [comment]
Seems that `ghci` is not really hanging, it still accepts input, but does not echo anything.  Providing arbitrary input fixes this after a while (several newlines work for me).  Furthermore, I can't reproduce this when passing `--plain`.  May it be that the interleaved output confuses the terminal (maybe when interleaving occurs just in the middle of some ASCII sequence)?

I'd really like to get rid of interleaved output.  From what you wrote in the [documentation of test-framework-quickcheck2](http://hackage.haskell.org/packages/archive/test-framework-quickcheck2/0.2.10/doc/html/Test-Framework-Providers-QuickCheck2.html), I assume that this requires modifications to QuickCheck.  Do you have any idea how much work that would be?

**Comment by batterseapower** [comment]
sol: QC2 has improved since I wrote that comment, so I've just uploaded a version of the QC2 provider (v0.2.12) that should fix the interleaved output in at least the case you mentioned. Can you try it and see if it helps?

**Comment by sol** [comment]
@batterseapower works here.  Thanks for that.
