### ISSUE TITLE
More concise output when running many tests

### ISSUE THREAD

**Issue by roelvandijk** [batterseapower/test-framework#2]
My numerals package [1] has a test-suite with 3383 tests. This number will likely grow in the future. When running this many tests you quickly loose the overview. Typically less than 50 of my ~3000 tests will fail. I would like to see at a glance which tests failed. Those that succeeded are not interesting. 

I would like an option to only display the results of tests that fail. This could be an option for defaultMain or an option for individual TestGroups.

[1] - http://code.haskell.org/numerals/

**Comment by batterseapower** [comment]
Added the --hide-successes command line option to v0.4.0 to do this. You can also set this option up in code by using something like:

```
main = do { ropts <- getArgs >>= interpretArgsOrExit; defaultMainWithOpts tests (ropts { ropt_hide_successes = Just True }) } 
```

**Comment by roelvandijk** [comment]
I tested this option and it works as advertised. Thanks!
