### ISSUE TITLE
Add a way to run IO before tests (but only if tests are going to run)

### ISSUE THREAD

**Issue by ocharles** [batterseapower/test-framework#26]
I currently have:

```
main :: IO ()
main = cleanState >> defaultMain tests
```

So I can make sure that I have a clean state before running integration tests. However, this runs even if I'm just running with `--help`. Ideally, this would only run if tests are actually going to run.

**Comment by batterseapower** [comment]
You could define tests as:

```
tests = buildTest (cleanState >> return old_tests)
```

Does that work?

**Comment by ocharles** [comment]
I actually had to do

``` haskell
main :: IO ()
main = defaultMain [buildTest (cleanState >> return (testGroup "All tests" tests))]
```

But that does work. I dunno if I lose anything by having to create that top level testGroup, but it seems fine.

**Comment by batterseapower** [comment]
Yeah sorry about that top-level test group. Perhaps I should add a way to build an "anonymous" test group, i.e. a combinator of type :: [Test] -> Test.

**Comment by ocharles** [comment]
I would be happy with that, but this is also fine. Your call! :)
