### ISSUE TITLE
Add support for running & reporting Smallcheck tests

### ISSUE THREAD

**Issue by hokster7** [batterseapower/test-framework#41]
See [Smallcheck](https://github.com/feuerbach/smallcheck).

**Comment by UnkindPartition** [comment]
It is already implemented. The package is called test-framework-smallcheck. The code is in a subdirectory of the repo you linked above.

**Comment by hokster7** [comment]
Oh, of course, I see!
I don't know how I missed that from Hackage, to be honest. Pardon me.
